DROP SCHEMA IF EXISTS TESTDATA;
CREATE SCHEMA IF NOT EXISTS TESTDATA;
SET SCHEMA TESTDATA;

DROP TABLE IF EXISTS MOVIE;

CREATE TABLE MOVIE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE varchar(255) ,
    DESCRIPTION varchar(255),
    AVAILABLE BOOLEAN,
    PRIMARY KEY (ID)
);